# Generated by Django 3.2.6 on 2025-10-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blango_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
